# Generated by Django 6.0.4 on 2026-05-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text='e.g. Python, Django, Tailwind', max_length=300)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('web', 'Web Development'), ('data', 'Data Analytics'), ('health', 'Health Tech'), ('cyber', 'Cybersecurity'), ('other', 'Other')], default='web', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
