# Generated by Django 6.0.4 on 2026-05-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='impact',
            field=models.TextField(blank=True, help_text='What was the result or outcome?'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, help_text='What problem does this project solve?'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, help_text='How does your project solve it?'),
        ),
    ]
