# Generated by Django 6.0.4 on 2026-05-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary shown in blog list. If empty, auto-generated from body.'),
        ),
    ]
